# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_column='text', max_length=300, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Fecha de comentario')),
            ],
            options={
                'db_table': 'Comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
            options={
                'db_table': 'Comment_State',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='current_state',
            field=models.ForeignKey(db_column='current_state', default=True, on_delete=django.db.models.deletion.CASCADE, to='comment.State'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_post',
            field=models.ForeignKey(db_column='id_post', default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
