# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(db_column='typeOfRol', max_length=50, unique=True, verbose_name='Tipo de rol')),
            ],
            options={
                'db_table': 'Rol',
                'managed': True,
            },
        ),
    ]
