# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:29
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(db_column='titulo', max_length=60, verbose_name='Titulo del post')),
                ('descr', models.TextField(blank=True, db_column='descripcion', max_length=60, null=True, verbose_name='Descripcion')),
                ('text', ckeditor.fields.RichTextField(db_column='texto', max_length=5000, verbose_name='Desarrollo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Fecha de publicacion')),
                ('files', models.ImageField(blank=True, db_column='files', default=None, null=True, upload_to='', verbose_name='Archivos')),
                ('id_category', models.ForeignKey(db_column='id_category', default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Post',
                'managed': True,
            },
        ),
    ]
